---
title: "Data Cleaning"
author: "Michael McManus (EPA)"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
```

# Read in the data
```{r}

catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_original)                         



```
# Make data tidy
Remove the notes and all columns because we don't need them.
"I" was discovered as an entry value for Chinook in 1955.
```{r}
catch_clean <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
    mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
    mutate(Chinook = as.numeric(Chinook))

head(catch_clean)
summary(catch_clean)
```

## Data QA
Deterimne which values were converted to NA by as.numeric
```{r}
# retain for future QA
i <- which(is.na(catch_clean$Chinook))
i
catch_original[i,]

```


## Convert to long format
We want data in a long format.
```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch") %>% 
    rename(catch_thousands = catch) %>% 
    mutate(catch = catch_thousands * 1000) %>% 
    select(-catch_thousands)

head(catch_long)



# cols identify variables that are pivoting into or if use - columns nto to pivot over
```

An example of pivot wider.
```{r}
catch_wider <- catch_long %>% 
    pivot_wider(names_from = "Year",
                values_from = "catch")

head(catch_wider)
```
# Summarize
```{r}
mean_region <- catch_long %>% 
  group_by(Region, species) %>%
  summarise(catch_mean = mean(catch),
            n_obs = n())

head(mean_region)

# group_by is splitting by region.
# summarise does the apply and combine.
```

```{r}
sockeye_catch <- catch_long %>% 
    filter(species == "Sockeye") %>% 
    group_by(Year) %>% 
    summarize(mean_catch = mean(catch)) %>% 
    arrange(desc(mean_catch))


head(sockeye_catch)
```

# Join to other data
```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"), stringsAsFactors = FALSE) %>% 
    select(code, mgmtArea)
head(region_defs)


catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))
head(catch_joined)

region_defs <- region_defs %>% 
  rename(Region = code, Region_Name = mgmtArea)

catch_joined <- left_join(catch_long, region_defs, by = c("Region"))

head(catch_joined)


```

```{r}
sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAI-039"),
                       stringsAsFactors = FALSE)

sites_df %>% 
  separate(site, c("island", "site_number"), "-", remove = FALSE)

dates_df <- data.frame(year = c("1930",
                                "1930",
                                "1930"),
                       month = c("12",
                                "12",
                                "12"),
                       day = c("14",
                               "15",
                               "16"),
                       stringsAsFactors = FALSE)

dates_df %>% 
  unite(date, year, month, day, sep = "-", remove = FALSE)
```